### ISSUE TITLE
User-feedback: Test if a bank user can install packages from here

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/universe#2]
Banks use CRAN to install the r2dii suite of packages. 
This is because, in our previous experience, many banks have not been able to install things from GitHub (it is blocked on their computers). 

It would be a good idea to:
* Find a bank that has trouble installing things from GitHub
* See if they can try to install the packages from this location

Avoiding CRAN and using R universe as our release platform **MAY** simplify our release process (still not even sure it is much better, but could be good to check)

**Comment by jdhoffa** [comment]
Self-assigning this so I don't forget :-)

**Comment by AlexAxthelm** [comment]
NB: when when working in restricted environments, the rule isn't "github is forbidden," it's "everything is forbidden, unless you get a specific carveout for it"

So someone who is using R may be able to argue without too much difficulty that CRAN is an essential carveout, but they may have just as much difficulty explaining to their security team why `rmi-pacta.r-universe.dev` should be on the allowlist as `github/rmi-pacta`

**Comment by AlexAxthelm** [comment]
But if someone can get that carveout, then yeah, using r-universe seems like it would make things a lot simpler

Especially for partners where we're iterating quickly / co-developing so probably not impossible in those cases. Definitely t think it's worth exploring. 

cc @jacobvjk for context.

**Comment by jdhoffa** [comment]
I think that is incorrect. 

At many banks the actual domain GitHub.com is specifically and invariably blocked, because they know it's meant to house software, and at some point someone in IT got scared of this. 

Source: I ran code at these banks and couldn't "carve out" access to GitHub no matter who I went through. 

Often, somebody else (usually a Quant) had at some point made the case that RStudio was a useful/ indispensable tool, and in most cases that same quant had already argued for access to CRAN as well, since R's utility is lower without packages.

**Comment by jdhoffa** [comment]
But, in any case, I'd like to shift towards working on fewer assumptions like these, and discussions of "what we think our users envs are like" and work towards actually getting real user feedback

**Comment by AlexAxthelm** [comment]
💯 on getting actual feedback. But also the variablity in org-level policies means that we'll probably always have to support the most restrictive version we can imagine. ☹️

**Comment by jdhoffa** [comment]
But yeah, I remember not even being able to log into GitHub at all from any of the banks computers, and I had to bring all the packages in on a USB lol

But somehow they were fine with CRAN

**Comment by cjyetman** [comment]
That sounds like two sides of the same coin... e.g. banks typically have a blacklist (instead of a whitelist), but if they're already using R there's a high probability that someone has already requested that CRAN be available, e.g. removed from their blacklist, or added to their whitelist

> banks typically have a blacklist (instead of a whitelist)

I question if this is really true, or if that's just the perception from a user perspective... seems like a high security environment would use a whitelist.

**Comment by jdhoffa** [comment]
A good discussion and all good questions to ask a bank!

I will track this issue in the P4B tech backlog

But in general, minimal updates to P4B are planned this quarter, so I don't expect we aim to gather user feedback until next quarter at least

**Comment by jacobvjk** [comment]
On projects that feature heavy co-developing of metrics/software: I think in the past year or so this has mainly been the case with supervisor related projects. In these cases, it seems like they were usually able to use GH to some extent, at least to download a repo as a zip file and install that locally. I don't want to generalise that yet, but it seems like banks may be the more restrictive environment.

**Comment by cjyetman** [comment]
@jdhoffa do you have this tracked somewhere else more appropriate? This seems more like a question to banks *if they're allowed to use this* than a technical question of if it can be used and/or how to technically facilitate that. tempted to close this issue

**Comment by jdhoffa** [comment]
They cannot!

Our main external users have IT teams that run a local mirror of CRAN, so that's the only real installation mechanism for them. Anything else (GitHub, R universe) is unlikely to be a useful delivery mechanism to those users

**Comment by AlexAxthelm** [comment]
If they're using a private CRAN Mirror(-ish, possibly a Posit repo), would they possibly be amenable to adding an R-universe to their allow list?

**Comment by jdhoffa** [comment]
I think what we're focusing on here is "what is the most user-friendly way to have people download our software", not "what is a possible way to have people download our software".

I bet on a case-by-case basis, if we had to, we could set up conversations with a particular users' IT team to see if they can make an exception... but the idiomatic and most likely simpler road is to publish on CRAN, which in general seems to already bo allowed (albeit probably only a subset of packages).

**Comment by jdhoffa** [comment]
So I guess if the options are:
1. publish our package to CRAN. get our package approved (by banks' IT team), they download it from their local CRAN mirror
2. publish to R-universe. get R-universe approved (by banks' IT team), beyond that, get our package approved (by banks' IT team)

option 1 seems to be the preferred approach.

**Comment by AlexAxthelm** [comment]
There is no approval process for R universe (beyond what we put it in it). Option 2 would look more like:
Publish to R universe, Bank approves _our_ R universe as a source, users can pull from their local CRAN-ish source

**Comment by jdhoffa** [comment]
Ah in my original comment, I meant "approved by Bank IT team", not approved by R Universe.

I edited my original comment for clarity. 

In either case, it adds 1 extra step of complexity for the Banks' IT approval process, since they not only have to get our software onto a white list but also a new and (likely unknown to them) package source
