### ISSUE TITLE
Assess if adding an R-Universe mirror allows a `Dockerfile + DESCRIPTION` install to function without `Remotes`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/universe#3]
NB (more of a question really, and not something we should solve in this PR): but I wonder if it would be possible/ interesting/ useful to just add or specify our R-universe instance as a package repository? so install from CRAN or RMI R-Universe. that way we don't need to jump through weird Remotes loops, the Dockerfile just knows that anything in our R-universe is valid to install. (obviously we would still need to sort out how to specify what version to install, but I think that is doable)

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/workflow.transition.monitor/pull/231#discussion_r1475594731_
            
Note: this issue isn't suggesting we actually do this, just assessing if it's feasible/ works well.

**Comment by cjyetman** [comment]
My initial guess was from the context of adding non-CRAN pkgs in DESCRIPTION `Depends:` without `Remotes:` *in an R package*, which I assume is not feasible because we can't control what CRAN repositories a user will have installed when they try to use it. But also this use case, I'm not 100% sure if it will work.

**Comment by jdhoffa** [comment]
Ah yeah totally fair point. It would sort of be abusing the purpose of a `DESCRIPTION` file in that case... I hadn't thought of it that way

**Comment by AlexAxthelm** [comment]
Looking at the R-universe docs+forums, I'm only seeing specifying `options(repos=<foo>)` as the way to point the install process at R-universe, but `Remotes:` seems to work pretty generally now that `pak` seems to have taken over the R-Lib ecosystem's install process.

**Comment by jdhoffa** [comment]
Ok!

In that case happy to close this, if we all agree that `DESCRIPTION` + `pak` + `Remotes` is suitable as an installation process for our R packages (for now anyway)

**Comment by cjyetman** [comment]
https://remotes.r-lib.org/articles/dependencies.html

and an open feature request for allowing `Remotes:` to specify an r-universe
https://github.com/r-lib/remotes/issues/618

**Comment by jdhoffa** [comment]
you posted the same link! But if they are working on it, maybe good to leave this issue open

**Comment by cjyetman** [comment]
updated link. does not sound imminent

**Comment by cjyetman** [comment]
To put this to the test, I made two files in one directory:

`Dockerfile`
``` Dockerfile
ARG PLATFORM="linux/amd64"
FROM --platform=$PLATFORM rocker/r-ver:4.3.1 AS base

RUN CRAN="https://packagemanager.posit.co/cran/__linux__/jammy/2024-04-05"; \
    pactaverse="https://rmi-pacta.r-universe.dev"; \
    echo "options(repos = c(CRAN = '$CRAN', pactaverse = '$pactaverse'))" \
    > "${R_HOME}/etc/Rprofile.site"

# install pak
RUN Rscript -e "install.packages('pak', repos = 'https://r-lib.github.io/p/pak/stable/')"

# copy in DESCRIPTION from this repo
COPY DESCRIPTION /DESCRIPTION

# install pactaverse (via Import in DESCRIPTION with no Remote)
RUN Rscript -e "pak::local_install_deps(ask = FALSE)"

CMD ["R", "-e", "library(pactaverse)"]
```

`DESCRIPTION`
```
Package: r.universe.docker.test
Title: Test install from r-universe.
Version: 0.0.0.9001
Authors@R:
    person("CJ", "Yetman", , "cj@cjyetman.com", role = c("aut", "cre"))
Description: Test install from r-universe.
Imports:
    pactaverse
```

then in a shell at that directory
``` sh
docker build -t test .
docker run --rm -ti test
```

and I get
``` sh
R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(pactaverse)
── Attaching core pactaverse packages ────────────────────────────────────── pactaverse 0.0.0.9000 ──
✔ pacta.data.preparation          0.1.0.9003     ✔ pacta.portfolio.audit           0.0.1.9000
✔ pacta.data.scraping             0.1.0.9000     ✔ pacta.portfolio.import          0.0.2     
✔ pacta.data.validation           0.0.0.9000     ✔ pacta.portfolio.report          0.4.1.9001
✔ pacta.executive.summary         0.1.1.9002     ✔ pacta.portfolio.utils           0.0.2.9000
✔ pacta.interactive.plot          0.0.0.9000     ✔ pacta.scenario.data.preparation 0.0.0.9000
✔ pacta.portfolio.allocate        0.0.2.9000     
── Conflicts ────────────────────────────────────────────────────────────── pactaverse_conflicts() ──
✖ pacta.data.validation::is_valid_isin() masks pacta.portfolio.import::is_valid_isin()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
 ____    ______  ____    ______  ______     
/\  _`\ /\  _  \/\  _`\ /\__  _\/\  _  \    
\ \ \L\ \ \ \L\ \ \ \/\_\/_/\ \/\ \ \L\ \   
 \ \ ,__/\ \  __ \ \ \/_/_ \ \ \ \ \  __ \  
  \ \ \/  \ \ \/\ \ \ \L\ \ \ \ \ \ \ \/\ \ 
   \ \_\   \ \_\ \_\ \____/  \ \_\ \ \_\ \_\
    \/_/    \/_/\/_/\/___/    \/_/  \/_/\/_/
```

**Comment by AlexAxthelm** [comment]
My vote would be to still keep `Remotes:` in the `DESCRIPTION`, rather than expecting install from R-universe. My thinking here is that while `remotes` doesn't work with `install.packages()`, it does work with the standard "extended (non-CRAN) package installation" infrastructure (`remotes::`, `pak::`, etc) in an explicit way. 

So a user is less likely to run into an issue where they have default `options()`, and fail to install (or install the wrong version) of one of our packages because they're pinging CRAN instead of our R-universe.

**Comment by cjyetman** [comment]
agreed... this is not something I really recommend, just answering the question posed by this issue.

I can kind of imagine instructing a user on the README to install a package that is not released on CRAN with e.g. `install.packages("pacta.portfolio.allocate", repos = "https://rmi-pacta.r-universe.dev")`, but that could alternatively suggest `devtools::install_github("RMI-PACTA/pacta.portfolio.allocate")` (though in that case they need to have `devtools` installed (or `remotes`)) so 🤷🏻

**Comment by AlexAxthelm** [comment]
Yeah, I think this is best handled in README for any given package, with something like:

## Installation

Install this package with: `pak::pak("RMI-PACTA/foo")`, or equivalently, `install.packages("foo", repos = "https://rmi-pacta.r-universe.dev")`

**Comment by jdhoffa** [comment]
I totally agree.

Are we happy to close this ticket out then without further action, and continue onward using `pak` as we have been?

**Comment by AlexAxthelm** [comment]
good to close from my side.
